spring:
  datasource:
    url: 'jdbc:h2:mem:sketchlab;MODE=PostgreSQL;database_to_upper=false'
    username: sa
    password: sa
    driver-class-name: org.h2.Driver
  jooq.sql_dialect: H2
  h2.console.enabled: true
  jackson.serialization:
    FAIL_ON_EMPTY_BEANS: false

server:
  session.cookie.name: 'LocationQuestSession'
  session.persistent: false

# Nerf the self-ad spam of jooq
logging.level.org.jooq.Constants: WARN

flyway.schemas: 'LOCATION_QUEST'