spring:
  datasource:
    url: jdbc:postgresql://localhost/locationquest
    username: locationquest
    password: locationquest
    driver-class-name: org.postgresql.Driver
  jooq.sql_dialect: POSTGRES
  h2.console.enabled: false
locationquest:
  domain: "https://autohike.eu"
